lob/lob-python

- README.md
- examples/check.py
- lob/api_requestor.py
- lob/version.py
- setup.py
- tests/test_lob.py
> Add version header

- lob/version.py
- setup.py
- tests/test_lob.py
- tests/test_postcard.py
> Fixed small test issues to get build working

- README.md
- examples/check.py
> feat(checks): added docs and example for check logo

- README.md
@lob/frontend-engineering-team
> fix(readme): examples for HTML

- examples/check.py
- lob/resource.py
- tests/test_bankaccount.py
- tests/test_check.py
@lob/api-engineering-team 
https://github.com/lob/lob-python/issues/67
> feat(bankAccounts): added support for verifying accounts

- examples/check.py
- examples/create_pdf.py
- examples/job.py
- examples/letter.py
- examples/postcard.py
- tests/test_area.py
@pon @leore 
https://github.com/lob/lob-api/issues/1505
> feat(examples): add html, data, and custom fonts

- README.md
- examples/README.md
- examples/csv_postcards/create_postcards.py
- examples/csv_postcards/input.csv
- examples/csv_postcards/postcard_back.html
- examples/csv_postcards/postcard_front.html
@lob/api-engineering-team -
I created a CSV example that uses HTML, custom fonts, and the data field. You can all use this as the template for adding to your wrapper.
Shoutout @mgartner for having the HTML already done.
> added HTML, csv example

- .travis.yml
- lob/api_requestor.py
- lob/compat.py
- lob/error.py
- lob/resource.py
- lob/version.py
- tests/test_object.py
- tests/test_packaging.py
- tests/test_route.py
Support python3.4. Wasn't too much so didn't need to add six or future as a dep.
> Python 3.4 support

- README.md
A couple links in the README were 404ing because they pointed to a folder that was renamed.
> Fix broken example links in README

- README.md
- examples/README.md
- examples/verify_and_create_letters_from_csv/input.csv
- examples/verify_and_create_letters_from_csv/letter.py
- examples/verify_and_create_letters_from_csv/letter_template.html
What: an example to verify and create letters
Why: allow customer to try out a test script that would take their csv file and generate letters for billing
Details:
- navigate to ```examples/verify_and_create_letters_from_csv/``` folder 
- run ```python letter.py input.csv```
- fixes: https://github.com/lob/lob-api/issues/1791
@russelltaylor05 @pon @mgartner @robinjoseph08 @elnaz
> feat(examples): added example to verify and create letters

- lob/resource.py
- tests/test_address.py
What: list parameters are serialized as arrays to the API endpoint
Why: allows the wrapper to use array parameters
Detail:
- Allows you to pass array parameters into the wrapper
- `lob.Address.list(include=['total_count'])`
@pon @mgartner @elnaz @robinjoseph08 @neelk07
> feat(params): single object list parameters serialized as arrays

- examples/create_postcards_from_csv/create_postcards_from_csv.py
- examples/verify_addresses_from_csv/verify_addresses_from_csv.py
- examples/verify_and_create_letters_from_csv/letter.py
What: 
- Allows examples to be run from any directory.
- Fixes bug where you can't run examples locally
- Fixes #84
> fix(examples): examples can be run from any directory

- lob/resource.py
- tests/test_postcard.py
What: 
- Add object support as arguments to ListableAPIResources
- Allows wrapper to use `metadata = { 'campaign' : 'NEWYORK2015' }` on `.list()` methods
- Fixes #86
> fix(metadata): add metadata support to ListableAPIResource

- examples/check.py
There weren't any changes necessary to the check tests or resource.
> fix(examples): rename check file to check_bottom

- README.md
Leore noticed that, from the project readme, if you click on the link for specific examples, we take you directly to the example source which may leave you wondering how to run that source. This changes the project readme links to point to the section of the example readme that examples how to run the example.
Fixes https://github.com/lob/lob-python/issues/96
> fix(readme): link to instructions for each example

- lob/api_requestor.py
> parse_response now handles 504 Gateway Timeout errors

- requirements.txt
What: Uses an older version of the requests package
Why: Latest update to requests uses unicodes for their error messages which are not supported in Python 3.2.6
> fix(dependencies): stricter requirements for requests package

- README.md
What: Removes downloads badge
Why: It was referencing a badge that no longer exists on PyPi
> fix(readme): Removes failing downloads badge

- .travis.yml
- setup.py
- tox.ini
This pull request alters the set of tested and listed python versions in the following ways:
- Remove support for Python 3.2. Pip has now dropped support for it, which
makes even running CI builds a challenge. It is also used by an [order-of-magnitude fewer people than use 3.3](http://www.randalolson.com/2016/09/03/python-2-7-still-reigns-supreme-in-pip-installs/) based on data from Randy Olsen.
- Add tox.ini to simplify running the build matrix locally.
- Add support for pypy and pypy3.
- Update classifiers in setup.py to include license (BSD) and the list of supported
versions. This means that the lob client is unequivocally shown as python 3 compatible
to tools like [`caniusepython3`](https://github.com/brettcannon/caniusepython3/blob/0d025e23c5ee25dd26111f26495858b5aa133236/caniusepyth …
> Update packaging / test metadata

- README.md
- examples/README.md
- examples/verify_addresses_from_csv/verify.py
What: Fixed up verify address example. Created in new PR because old one had strange git issues and I decided a clean install was the way to go. Original (with comments) is [here](https://github.com/lob/lob-python/pull/119)
Why: Part of an accross the board improvement on python.
> refactor(verify): clean up verify address from csv example

- .travis.yml
- requirements.txt
- tox.ini
**What**
- `pypy3` uses Python 3.2  which caused major headaches for Python package maintainers and as such they simply decided to drop support for such version. `coverage`, one of our dependencies now explicitly forbids the use of Python 3.2 so the builds have started failing. We stopped supporting Python 3.2 since #115 so there's no point in testing against it anymore.
- Now that we're no longer testing against Python 3.2, we can upgrade our coverage version once more.
- We had previously limited our version of coverage in order to support Python 3.2 #89
**Why**
Since I was the last person to push a commit, I'm the one who started getting the annoying messages that the build is broken... σ(￣、￣〃)
> chore(tests): remove pypy3 and add python 3.6

- README.md
- lob/__init__.py
- lob/resource.py
- tests/test_address.py
- tests/test_intl_verification.py
- tests/test_us_verification.py
> feat(verifications): add us and intl verification endpoints ENG-2767

- lob/resource.py
**What**
**Why**
Python2 creates a copy of the dictionary you call `.items()` however Python3 returns an iterator. As such when using Python3, you'll be modifying the same object which you're currently iterating which causes problems (Python3 actually detects this and throws a `RuntimeError`).
Fixes #134
> chore(py3): copy params before iterating and mutating

- .gitignore
- examples/check.py
- examples/create_checks_from_csv/check.py
- examples/letter.py
- examples/postcard.py
- examples/verify_addresses_from_csv/verify.py
- lob/__init__.py
- lob/api_requestor.py
- lob/error.py
- lob/resource.py
- setup.py
- tests/test_address.py
- tests/test_area.py
- tests/test_bankaccount.py
- tests/test_check.py
- tests/test_intl_verification.py
- tests/test_letter.py
- tests/test_lob.py
- tests/test_postcard.py
- tests/test_route.py
- tests/test_us_verification.py
- tests/test_us_zip_lookup.py
Fixes most linter warnings other than "imported but unused" errors in `__init__.py` and "line too long" errors. 
We should be following the pep8 style guide as much as possible. If we want to adhere to the line character limit, I'll fix that up too.
> chore(lint): fix most linter warnings

- lob/api_requestor.py
- lob/resource.py
Removes code that was used to support parameters from a [deprecated endpoint](https://github.com/lob/lob-python/pull/121).
We shouldn't have useless code lying around.
> fix(tests): remove code support for deprecated endpoint

- lob/api_requestor.py
- tests/test_us_verification.py
**What** 
- Allow us to send a `query` values with CreateableAPIResources.
- Minor code cleanup (deleting unnecessary new lines)
> feat(CreateableResource): allow query params in creatable resources

- lob/api_requestor.py
- tests/test_us_verification.py
**What**
- In order to override the existing Lob Version set in the library, simply set a `lob_version` argument in the Lob API call. For example
```python
lob.USVerification.create(
primary_line='185 Berry St',
city='San Francisco',
state='CA',
zip_code='94107',
lob_version='2018-03-30'
)
```
**Why**
Adding extra functionality to our library. Some customers want to use the latest version for new products but aren't able to upgrade their entire existing integration just yet.
> feat(api): allow overriding Lob-Version per request

- README.md
- examples/check.py
- examples/create_checks_from_csv/check.py
- examples/create_letters_from_csv/letters.py
- examples/create_postcards_from_csv/postcards.py
- examples/letter.py
- examples/postcard.py
- examples/verify_addresses_from_csv/verify.py
- tests/test_address.py
- tests/test_bankaccount.py
- tests/test_check.py
- tests/test_intl_verification.py
- tests/test_letter.py
- tests/test_postcard.py
- tests/test_us_autocompletion.py
- tests/test_us_verification.py
- tests/test_us_zip_lookup.py
* Removes all lob api keys from source code
* Updates testing instructions in README
No need to expose API keys
> test(api-key): remove lob api key from tests and examples

- examples/check.py
- examples/create_checks_from_csv/check.py
- examples/create_letters_from_csv/letters.py
- examples/create_letters_from_csv_async/letters.py
- examples/create_postcards_from_csv/postcards.py
- examples/letter.py
- examples/postcard.py
- examples/verify_addresses_from_csv/verify.py
- lob/api_requestor.py
- tests/test_check.py
- tests/test_letter.py
- tests/test_postcard.py
* Makes our p/l/c examples python3-compatible
* Adds back logic to support nested objects (e.g. payload['to']['metadata']['department'])
* Python 2 is on its way out, so our examples should be python3-compatible
* The python library should be able to support nested objects for things like `metadata`.
> fix(examples): make examples python3 and make metadata work

- .bumpversion.cfg
- .travis.yml
- Pipfile
- Pipfile.lock
- README.md
- lob/version.py
- requirements.txt
- setup.py
- tox.ini
This PR contains a few chore commits to improve the way we manage our dependencies and make releases.
* Updates to use pipenv, which is now the recommended way to manage virtualenvs
* Updates CI & metadata versions to support Python 3.7
* Adds bumpversion, a utility for, ahem, bumping the version consistently
* Populates the project description on https://pypi.org/project/lob/ (which is currently, sadly, empty)
> chore(release): Improve release & version hygiene

- tests/test_intl_verification.py
Prevents the test from erroring, now that we've enabled capability for international verification test mode
> feat(intl-verification): updating python github library

- lob/api_requestor.py
- tests/test_check.py
- tests/test_letter.py
- tests/test_postcard.py
- tests/test_us_verification.py
* Updates `api_requestor` to allow nested structs and lists for `merge_variables`
* Adds some basic tests for the new template syntax (conditionals, loops, objects)
This allows the client to send nested merge variables to go along with the advanced templating syntax feature
> chore(template-syntax): allow nested merge variables

- README.md
- lob/version.py
- setup.py
**What**
Updates README.md and bumps client library version identifier from 4.0.2 to 4.1.0
**Why**
Cutting new release with added self mailer support
> chore: bump version 4.0.2 -> 4.1.0

- examples/README.md
- examples/cards/card.pdf
- examples/create_card.py
- examples/create_card_order.py
- examples/postcard.py
- examples/postcard_idempotent.py
- examples/postcard_localfile.py
- examples/postcard_send_date.py
- examples/postcard_template.py
- lob/__init__.py
- lob/resource.py
- tests/pdfs/card.pdf
- tests/test_card.py
- tests/test_card_order.py
**Why**
As we rollout Card-Affix for GA, we want to expose this functionality through our public SDK's. We will need to create and configure the necessary libraries for our card affix endpoints
**What**
- Create a resource for cards
- Create a resource for card orders, which require being passed a `card_id` since this mirrors the functionality of our card_orders endpoint (e.g. `GET/POST v1/cards/{card_id}/orders`
- Create tests for cards
- Create tests for card orders
- Create an example file using the combined functionality
> [feat]: Updated SDK for cards and card orders

- examples/create_card.py
- lob/resource.py
- tests/test_card.py
**What and Why**
We have an endpoint available to update a Card. We now expose that route through the SDK.
> [fix] Cards: Added Card.update route

- .gitignore
- .travis.yml
- Pipfile
- Pipfile.lock
- README.md
- tox.ini
Nosetests has been unmaintained for years.
https://nose.readthedocs.io/en/latest/#note-to-users
pytest is now the defacto standard for python testing. 
https://docs.pytest.org/en/6.2.x/index.html
pytest can also execute and run unittest and nosetests tests.
https://docs.pytest.org/en/6.2.x/nose.html?highlight=nosetests
There are some usages of nose that are incompatible, but none of our tests are written that way.
> replace nosetests with Pytest

- .github/workflows/forked_repos.yaml
Because of security concerns with Github Secrets, we need to put in another GH action to be able to run tests (which make sure of the GH Secrets to hold the API keys).
> added another GH action to handle forked repos

- README.md
[ticket](https://lobsters.atlassian.net/browse/DXP-1196)
Won't be valid till lob-python-sdk is merged into lob-python and released.
> prep README with migration details 

- CODE_SNIPPETS.md
- MIGRATION.md
- docs/UsVerificationsWritable.md
- lob_python/model/us_verifications_writable.py
- test/Integration/test_us_autocompletions_api.py
- test/assets/lobster-family.csv
[GC-1940](https://lobsters.atlassian.net/browse/GC-1940)
Updates Lob's address from "210 King Street, 94107" to "2261 Market Street STE 5668, 94114"
Tests fail for this PR. However, I checked and [they also fail on main](https://github.com/lob/lob-python/actions/runs/7542197758) and failed on [the previous PR](https://github.com/lob/lob-python/pull/205), so these failures are unrelated to this PR.
I created [GC-2168](https://lobsters.atlassian.net/browse/GC-2168) to fix these tests.
[GC-1940]: https://lobsters.atlassian.net/browse/GC-1940?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[GC-2168]: https://lobsters.atlassian.net/browse/GC-2168?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> GC-1940/updates lob address

- lob_python/model/letter.py
- setup.py
Following [this slack thread](https://lob.slack.com/archives/C3DQ3K9U6/p1709851721432059), given we now allow tracking event for letters, we are removing the `max_items: 0` validation from `letters.tracking_events`
[GC-2518](https://lobsters.atlassian.net/browse/GC-2518)
Relates to https://github.com/lob/sdks_openapi_gen/pull/341
[GC-2518]: https://lobsters.atlassian.net/browse/GC-2518?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> GC-2518/fixes letters tracking event validation
