examples/job.py, examples/postcard.py
=> added name to example requests

lob/api_requestor.py
@lob/api-engineering-team 
Fixes #33
=> fix(coverage): increase to 100%

lob/version.py, setup.py
@pon @leore 
So merging this is all I would need to do to update the version?
=> Updated version

examples/create_postcards_from_csv/create_postcards_from_csv.py
@elnaz @robinjoseph08 @brianseitel
=> fixes example for Windows

requirements.txt
This should fix the python 3.2 builds.
https://github.com/travis-ci/travis-ci/issues/4866#issuecomment-144489980
@robinjoseph08 @brianseitel @mgartner
=> Upgrade coverage to version 4

examples/check.py, tests/test_bankaccount.py
Updates bank account tests and the check example.
=> Support API version 2016-03-21

CONTRIBUTING.md, LICENSE, examples/check.py, examples/job.py, examples/letter.py, examples/postcard.py
JIRA: ENG-894
What: Added license and contributing files. Supremely simple change -- virtually copied and pasted from node version with relevant links changed. Also made one stylistic change on the wrappers, merely adding an extra line.
Why: Generating consistency amongst all the wrappers we have!
=> chore(license/contributing): Added license file and contributing file

README.md, requirements.txt, setup.py
What: Update the README to reflect recent changes to the project setup
Why: Removed 3.2 support and the project also worked on 3.5
=> fix(readme): Remove 3.2 from the readme and add 3.5

examples/README.md, examples/create_checks_from_csv/check.html, examples/create_checks_from_csv/check.py, examples/create_checks_from_csv/input.csv, examples/create_postcards_from_csv/postcards.py
JIRA: ENG-1199
- Adds create checks from csv example
- Fixes letters from csv example to have better error checking
- Cosmetic fix in postcards
- To have consistent examples for our core products
=> [WIP] feat(checks): adds create check from csv example

examples/create_checks_from_csv/check.py, examples/create_letters_from_csv/letters.py, examples/create_postcards_from_csv/postcards.py, examples/verify_addresses_from_csv/verify.py
=> fix(examples): make examples compatible with python 2 and 3

README.md, examples/README.md, examples/check.py, examples/create_checks_from_csv/check.py, examples/create_letters_from_csv/letters.py, examples/create_postcards_from_csv/postcards.py, examples/letter.py, examples/postcard.py, tests/test_letter.py, tests/test_postcard.py
What: update examples to use merge_variables
Why: new HTML feature publish new version
=> chore(resources): update to use merge_variables

.gitignore, lob/resource.py, tests/test_check.py, tests/test_letter.py, tests/test_postcard.py
Finishes implementation of DELETE method on letters and postcards. Also implements tests for DELETE method on letters, checks, and postcards
=> feat(delete) Add DELETE method on checks, letters, and postcards

lob/api_requestor.py, tests/test_postcard.py
WHAT: adds capability to pass in idempotency headers
WHY: because I need to finish my intern project
=> feat(idempotent-headers): adds capability to pass in idempotency headers

tests/test_address.py, tests/test_check.py, tests/test_postcard.py
Capitalize test cases that are failing due to auto-verification.
Tests should reflect the new behavior we're expecting.
=> fix(tests): capitalize failing tests cases

tests/test_intl_verification.py
=> test(intl): Update international verification tests

README.md, lob/__init__.py, lob/resource.py, tests/test_us_autocompletion.py
* Adds US Autocompletion resource + test
* Adds US Autocompletion info to the README
* Customers should be able to use our libraries to make autocompletion requests
=> feat(us-autocompletions): add USAutocompletions

examples/create_letters_from_csv_async/input.csv, examples/create_letters_from_csv_async/letter.html, examples/create_letters_from_csv_async/letters.py
We're seeing an increase in the number of requests for an async example of calling lob. This PR adds an async version of our existing create letter example.
=> feat(async): Add async letter creation example.

tests/test_self_mailer.py
Fixes a failing test case due to an upstream bug fix in the Lob API
=> fix(self-mailers): Fix failing test due to upstream bug fix

README.md, lob/__init__.py, lob/resource.py, tests/test_us_reverse_geocode_lookup.py
- Adds in the reverse geocode resource and tests
=> feat(us_verifications) Adding in Reverse Geocoding Endpoint

examples/create_card_order.py, lob/version.py, setup.py, tests/test_card_order.py
We have tweaked the parameters and requirements for the Cards API. This PR updates the SDK to reflect that.
=> [fix] Cards: Updated tests to reflect changed API contract 

lob/__init__.py, lob/resource.py, tests/test_billing_group.py
Add support for billing groups: https://docs.lob.com/#tag/Billing-Groups.
=> Add billing group support

.github/workflows/run_tests.yml, lob_python/model/campaign_creative.py, lob_python/model/creative_response.py, lob_python/model/creative_writable.py, lob_python/model/letter_details_returned.py
Still not 100% sure that there isn't a param missing for these typedefs, but this should at least allow the code to compile.
=> GC-1915/Remove Leading Comma
